syntax = "proto3";

package olvid.daemon.admin.v1;

import "olvid/daemon/datatypes/v1/backup.proto";
import "olvid/daemon/datatypes/v1/client_key.proto";
import "olvid/daemon/datatypes/v1/identity.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** BackupKeyGet
 ** Get your current backup key.
 ** ⚠️ Store it in a safe place, this key allows to restore this daemon identities on another device/daemon.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `INTERNAL`
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message BackupKeyGetRequest {}
message BackupKeyGetResponse {
  string backup_key = 1;
}

/*
 ** BackupKeyRenew
 ** Discard previous backup key and create a new one.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `INTERNAL`
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message BackupKeyRenewRequest {}
message BackupKeyRenewResponse {
  string backup_key = 1;
}

/*
 ** BackupGet
 ** Show the backup associated with a backup key.
 ** It contains an admin backup with admin client key and associated storage,
 ** and snapshots for each identity.
 **
 ** **Error codes**:
 ** `INVALID_ARGUMENT`: cannot access backup.
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message BackupGetRequest {
  string backup_key = 1;
}
message BackupGetResponse {
  datatypes.v1.Backup backup = 1;
}

/*
 ** BackupNow
 ** Force a new backup.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `INTERNAL`
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message BackupNowRequest {}
message BackupNowResponse {}

/*
 ** BackupRestoreDaemon
 ** Restore a complete daemon instance.
 ** This is only possible on a blank daemon instance.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `INVALID_ARGUMENT`: your daemon database is not empty.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message BackupRestoreDaemonRequest {
  // key of the backup to restore
  string backup_key = 1;
  // specify a name for this new device (*daemon* is set as default)
  optional string new_device_name = 2;
}
message BackupRestoreDaemonResponse {
  repeated datatypes.v1.Identity restored_identities = 1;
  repeated datatypes.v1.ClientKey restored_admin_client_keys = 2;
  repeated datatypes.v1.ClientKey restored_client_keys = 3;
}

/*
 ** BackupRestoreAdminBackup
 ** Restore admin data of a backup (admin client keys and associated storage).
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `INTERNAL`
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message BackupRestoreAdminBackupRequest {
  // key of the backup to restore
  string backup_key = 1;
}
message BackupRestoreAdminBackupResponse {
  repeated datatypes.v1.ClientKey restored_admin_client_keys = 1;
}

/*
 ** BackupRestoreProfileSnapshot
 ** Restore a identity from a backup.
 ** Pass the identity snapshot id you want to restore.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `NOT_FOUND`: snapshot not found.
 ** `INVALID_ARGUMENT`: identity already exists locally.
 ** `INTERNAL`
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message BackupRestoreProfileSnapshotRequest {
  // key of the backup to restore
  string backup_key = 1;
  // id of the spnapshot to restore
  string id = 2;
  // specify a name for this new device (*daemon* is set as default)
  optional string new_device_name = 3;
}
message BackupRestoreProfileSnapshotResponse {
  datatypes.v1.Identity restored_identity = 1;
  repeated datatypes.v1.ClientKey restored_client_keys = 2;
}
