syntax = "proto3";

package olvid.daemon.admin.v1;

import "olvid/daemon/datatypes/v1/identity.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** IdentityList
 ** List all identities on this daemon.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `INVALID_ARGUMENT`: invalid filter.
 ** `INTERNAL`
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentityListRequest {
  optional datatypes.v1.IdentityFilter filter = 1;
}
message IdentityListResponse {
  repeated datatypes.v1.Identity identities = 1;
}

/*
 ** IdentityAdminGet
 ** Get a specific identity, identified by its id.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `NOT_FOUND`: identity not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentityAdminGetRequest {
  uint64 identity_id = 1;
}
message IdentityAdminGetResponse {
  datatypes.v1.Identity identity = 1;
}

/*
 ** IdentityAdminGetBytesIdentifier
 ** Get identity long term identifier.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `NOT_FOUND`: identity not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentityAdminGetBytesIdentifierRequest {
  uint64 identity_id = 1;
}
message IdentityAdminGetBytesIdentifierResponse {
  bytes identifier = 1;
}

/*
 ** IdentityAdminGetInvitationLink
 ** Get identity invitation link.
 ** This link allows other identities to send invitations.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `NOT_FOUND`: identity not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentityAdminGetInvitationLinkRequest {
  uint64 identity_id = 1;
}
message IdentityAdminGetInvitationLinkResponse {
  string invitation_link = 1;
}

/*
 ** IdentityAdminDownloadPhoto
 ** Download profile photo of an identity.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `NOT_FOUND`: identity not found.
 ** `INTERNAL`
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentityAdminDownloadPhotoRequest {
  uint64 identity_id = 1;
}
message IdentityAdminDownloadPhotoResponse {
  bytes photo = 1;
}

/*
 ** IdentityNew
 ** Create a new identity on this daemon.
 ** You must specify at least a non blank firstname or lastname in identity_details.
 ** You can specify a server_url to create identity on, by default it uses Olvid main distribution server.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `INVALID_ARGUMENT`: one of first name or last name must be non empty.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentityNewRequest {
  datatypes.v1.IdentityDetails identity_details = 1;
  optional string server_url = 2;
}
message IdentityNewResponse {
  datatypes.v1.Identity identity = 1;
}

/*
 ** IdentityKeycloakNew
 ** Create a new keycloak managed identity on this daemon.
 ** Pass the configuration link you created in the keycloak management console.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `INTERNAL`
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentityKeycloakNewRequest {
  string configuration_link = 1;
}
message IdentityKeycloakNewResponse {
  datatypes.v1.Identity identity = 1;
}

/*
 ** IdentityDelete
 ** Delete an identity on this daemon, identified by its id.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: an admin client key is necessary.
 ** `NOT_FOUND`: identity not found.
 ** `INTERNAL`
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentityDeleteRequest {
  uint64 identity_id = 1;
  optional bool delete_everywhere = 2; // delete from every device and notify your contacts for deletion
}
message IdentityDeleteResponse {}
