syntax = "proto3";

package olvid.daemon.command.v1;

import "olvid/daemon/datatypes/v1/contact.proto";
import "olvid/daemon/datatypes/v1/invitation.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** ContactList
 ** List contacts for current identity.
 ** Pass a filter to select only contacts that match specific criteria.
 **
 ** **Error codes**:
 ** `INVALID_ARGUMENT`: invalid filter.
 ** `UNAUTHENTICATED`: client key is invalid
 ** `INTERNAL`
 */
message ContactListRequest {
  optional datatypes.v1.ContactFilter filter = 1;
}
message ContactListResponse {
  repeated datatypes.v1.Contact contacts = 1;
}

/*
 ** ContactGet
 ** Get a contact by id.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contact not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message ContactGetRequest {
  uint64 contact_id = 1;
}
message ContactGetResponse {
  datatypes.v1.Contact contact = 1;
}

/*
 ** ContactGetBytesIdentifier
 ** Get a contact identity as bytes.
 ** This is useful to have a long term identifier for a contact, backup-proof, and common to any device.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contact not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message ContactGetBytesIdentifierRequest {
  uint64 contact_id = 1;
}
message ContactGetBytesIdentifierResponse {
  bytes identifier = 1;
}

/*
 ** ContactGetInvitationLink
 ** Get a contact invitation link.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contact not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message ContactGetInvitationLinkRequest {
  uint64 contact_id = 1;
}
message ContactGetInvitationLinkResponse {
  string invitation_link = 1;
}

/*
 ** ContactDelete
 ** Delete a contact by id.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contact not found.
 ** `INVALID_ARGUMENT`: contact is still in a group.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message ContactDeleteRequest {
  uint64 contact_id = 1;
}
message ContactDeleteResponse {}

/*
 ** ContactIntroduction
 ** Introduce two of your contacts together.
 ** They will both receive an invitation to accept.
 ** If each of the two accepts, they will be added to each other's contact book and can exchange.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: first or second contact not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message ContactIntroductionRequest {
  uint64 first_contact_id = 1;
  uint64 second_contact_id = 2;
}
message ContactIntroductionResponse {}

/*
 ** ContactInviteToOneToOneDiscussion
 ** Invite a non one-to-one contact to have a one-to-one discussion.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contact not found.
 ** `INVALID_ARGUMENT`: contact already has a one to one discussion.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message ContactInviteToOneToOneDiscussionRequest {
  uint64 contact_id = 1;
}
message ContactInviteToOneToOneDiscussionResponse {
  datatypes.v1.Invitation invitation = 1;
}

/*
 ** ContactDowngradeOneToOne
 ** Downgrade a one-to-one contact to a non one-to-one contact.
 ** This will lock current discussion with this contact.
 ** The contact will always be in your contact book and common groups but you will no longer be able to exchange direct message.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contact not found.
 ** `INVALID_ARGUMENT`: contact is not one to one, does not have established channel or does not support one to one downgrade.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message ContactDowngradeOneToOneDiscussionRequest {
  uint64 contact_id = 1;
}
message ContactDowngradeOneToOneDiscussionResponse {}

/*
 ** ContactDownloadPhoto
 ** Download the contact profile picture as bytes, or the group picture, or the generated image for this discussion.
 ** Pictures are always jpeg files with a maximum of 1080x1080 resolution.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contact not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message ContactDownloadPhotoRequest {
  uint64 contact_id = 1;
}
message ContactDownloadPhotoResponse {
  bytes photo = 1;
}

/*
 ** ContactRecreateChannels
 ** Reset cryptographic channels with a contact.
 ** USE CAREFULLY: this might fix some issues but every non sent / received messages will be lost.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contact not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message ContactRecreateChannelsRequest {
  uint64 contact_id = 1;
}
message ContactRecreateChannelsResponse {}
