syntax = "proto3";

package olvid.daemon.command.v1;

import "olvid/daemon/datatypes/v1/discussion.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** DiscussionList
 ** List discussions for current identity.
 ** Pass a filter to select only discussions that match specific criteria.
 **
 ** **Error codes**:
 ** `INVALID_ARGUMENT`: invalid filter.
 ** `NOT_FOUND`: filter contact not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message DiscussionListRequest {
  optional datatypes.v1.DiscussionFilter filter = 1;
}
message DiscussionListResponse {
  repeated datatypes.v1.Discussion discussions = 1;
}

/*
 ** DiscussionGet
 ** Get discussion by id.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: discussion not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message DiscussionGetRequest {
  uint64 discussion_id = 1;
}
message DiscussionGetResponse {
  datatypes.v1.Discussion discussion = 1;
}

/*
 ** DiscussionGetBytesIdentifier
 ** Get a discussion identifier as bytes.
 ** This is useful to have a long term identifier for a discussion, backup-proof, and common to any device.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: discussion not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message DiscussionGetBytesIdentifierRequest {
  uint64 discussion_id = 1;
}
message DiscussionGetBytesIdentifierResponse {
  bytes identifier = 1;
}

/*
 ** DiscussionGetByContact
 ** Get discussion by contact id.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: discussion not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message DiscussionGetByContactRequest {
  uint64 contact_id = 1;
}
message DiscussionGetByContactResponse {
  datatypes.v1.Discussion discussion = 1;
}

/*
 ** DiscussionGetByGroup
 ** Get discussion by group id.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: discussion not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message DiscussionGetByGroupRequest {
  uint64 group_id = 1;
}
message DiscussionGetByGroupResponse {
  datatypes.v1.Discussion discussion = 1;
}

/*
 ** DiscussionEmpty
 ** Delete all messages and attachments in a discussion.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: discussion not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message DiscussionEmptyRequest {
  uint64 discussion_id = 1;
}
message DiscussionEmptyResponse {}

/*
 ** DiscussionDownloadPhoto
 ** Download a discussion photo.
 ** The photo can be the contact photo, the group photo, or a generated image for the discussion if a specific image was not set.
 ** Photos are always jpeg files with a maximum of 1080x1080 resolution.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: discussion not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message DiscussionDownloadPhotoRequest {
  uint64 discussion_id = 1;
}
message DiscussionDownloadPhotoResponse {
  bytes photo = 1;
}

/*
 ** DiscussionLockedList
 ** List locked discussions.
 ** Locked discussions are discussions associated to a deleted contact or a group you left.
 ** Messages in those discussions are still accessible, but you cannot post new messages in those discussions.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message DiscussionLockedListRequest {}
message DiscussionLockedListResponse {
  repeated datatypes.v1.Discussion discussions = 1;
}

/*
 ** DiscussionLockedDelete
 ** Delete a locked discussion by id.
 ** This will delete discussion and its content, including messages and attached files.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: discussion not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message DiscussionLockedDeleteRequest {
  uint64 discussion_id = 1;
}
message DiscussionLockedDeleteResponse {}
