syntax = "proto3";

package olvid.daemon.command.v1;

import "olvid/daemon/datatypes/v1/group.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** List groups for current identity.
 ** Pass a filter to select only groups that match specific criteria.
 **
 ** **Error codes**:
 ** `INVALID_ARGUMENT`: invalid filter.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message GroupListRequest {
  optional datatypes.v1.GroupFilter filter = 1;
}
message GroupListResponse {
  repeated datatypes.v1.Group groups = 1;
}

/*
 ** GroupGet
 ** Get group by id.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: group not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message GroupGetRequest {
  uint64 group_id = 1;
}
message GroupGetResponse {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupGetBytesIdentifier
 ** Get a group identifier as bytes.
 ** This is useful to have a long term identifier for a group, backup-proof, and common to any device.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: group not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message GroupGetBytesIdentifierRequest {
  uint64 group_id = 1;
}
message GroupGetBytesIdentifierResponse {
  bytes identifier = 1;
}

/*
 ** GroupNewStandardGroup
 ** Create a new standard group.
 ** In a standard group all members are administrators, everyone can edit group details and manage group members.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contacts not found.
 ** `INVALID_ARGUMENT`: at least one contact does not support group v2.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message GroupNewStandardGroupRequest {
  optional string name = 1;
  optional string description = 2;
  repeated uint64 admin_contact_ids = 3;
}
message GroupNewStandardGroupResponse {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupNewControlledGroup
 ** Create a new controlled group.
 ** In a controlled group Administrators are specifically designated and they can edit group details and manage group members.
 ** Simple members cannot manage the group but they can post messages, attachments and reactions.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contacts not found.
 ** `INVALID_ARGUMENT`: a contact cannot be in admins and members at the same time / at least one contact does not support group v2.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message GroupNewControlledGroupRequest {
  optional string name = 1;
  optional string description = 2;
  repeated uint64 admin_contact_ids = 3;
  repeated uint64 contact_ids = 4;
}
message GroupNewControlledGroupResponse {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupNewReadOnlyGroup
 ** Create a new read-only group.
 ** In read only groups only group administrators can manage the group and post messages.
 ** Other users can only react to messages.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contacts not found.
 ** `INVALID_ARGUMENT`: a contact cannot be in admins and members at the same time / at least one contact does not support group v2.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message GroupNewReadOnlyGroupRequest {
  optional string name = 1;
  optional string description = 2;
  repeated uint64 admin_contact_ids = 3;
  repeated uint64 contact_ids = 4;
}
message GroupNewReadOnlyGroupResponse {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupNewAdvancedGroup
 ** Create a new advanced group.
 ** An advanced group allows to manually assign permissions to all members.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: contacts not found.
 ** `INVALID_ARGUMENT`: a contact cannot be in admins and members at the same time / at least one contact does not support group v2.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message GroupNewAdvancedGroupRequest {
  optional string name = 1;
  optional string description = 2;
  optional datatypes.v1.Group.AdvancedConfiguration advanced_configuration = 3;
  repeated datatypes.v1.GroupMember members = 4;
}
message GroupNewAdvancedGroupResponse {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupDisband
 ** Close a group, every member will leave the group and the discussion will be locked for everyone.
 ** Only administrators are allowed to disband a group.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: group not found.
 ** `INVALID_ARGUMENT`: impossible to disband a keycloak group.
 ** `PERMISSION_DENIED`: you are not admin in this group.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message GroupDisbandRequest {
  uint64 group_id = 1;
}
message GroupDisbandResponse {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupLeave
 ** Leave a group, the discussion will still exists for other group members.
 ** Any group member can leave a group at any time, except if you are the last administrator in this group (a group must always have an administrator).
 **
 ** **Error codes**:
 ** `NOT_FOUND`: group not found.
 ** `INVALID_ARGUMENT`: impossible to disband a keycloak group / you cannot leave a group if you are the only group administrator.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message GroupLeaveRequest {
  uint64 group_id = 1;
}
message GroupLeaveResponse {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupUpdate
 ** Update a group by modifying a Group object retrieved from groupList of groupGet.
 ** Supported modifications:
 ** - Add a member: create a new GroupMember and add it to members field
 ** - Remove a member: remove associated GroupMember from members field
 ** - Remove a pending member: remove associated GroupPendingMember from pendingMembers field
 ** - Update (pending) member permissions: update permissions in permissions field in GroupMember or GroupPendingMember
 ** - Update group name: modify name field
 ** - Update group description: modify description field
 ** Every other modifications will be ignored. You must keep groupId field properly set.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: group not found.
 ** `PERMISSION_DENIED`: you are not admin in this group.
 ** `INVALID_ARGUMENT`: the new group version has not been updated / new group member not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message GroupUpdateRequest {
  datatypes.v1.Group group = 1;
}
message GroupUpdateResponse {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupSetPhoto
 ** Set a new photo for a group.
 ** The photo can be jpeg or png but will be converted to jpeg and resolution will be limited to 1080x1080.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: group not found.
 ** `PERMISSION_DENIED`: you are not admin in this group.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message GroupSetPhotoRequestMetadata {
  uint64 group_id = 1;
  string filename = 2;
  uint64 file_size = 3;
}
message GroupSetPhotoRequest {
  oneof request {
    GroupSetPhotoRequestMetadata metadata = 1;
    bytes payload = 2;
  }
}
message GroupSetPhotoResponse {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupDownloadPhoto
 ** Download the group picture as bytes, or the generated image for this group.
 ** Pictures are always jpeg files with a maximum of 1080x1080 resolution.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: group not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message GroupDownloadPhotoRequest {
  uint64 group_id = 1;
}
message GroupDownloadPhotoResponse {
  bytes photo = 1;
}

/*
 ** GroupUnsetPhoto
 ** Unset the current group picture if there is one.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: group not found.
 ** `INVALID_ARGUMENT`: group does not have a photo.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message GroupUnsetPhotoRequest {
  uint64 group_id = 1;
}
message GroupUnsetPhotoResponse {
  datatypes.v1.Group group = 1;
}
