syntax = "proto3";

package olvid.daemon.command.v1;

import "olvid/daemon/datatypes/v1/identity.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** IdentityGet
 ** Get your identity details.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message IdentityGetRequest {}
message IdentityGetResponse {
  datatypes.v1.Identity identity = 1;
}

/*
 ** IdentityGetBytesIdentifier
 ** Get your Olvid identity as bytes.
 ** This is useful to have a long term identifier for an identity, backup-proof, and common to any device.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: identity not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message IdentityGetBytesIdentifierRequest {}
message IdentityGetBytesIdentifierResponse {
  bytes identifier = 1;
}

/*
 ** IdentityGetInvitationLink
 ** Get your invitation link. This link can be sent to other Olvid users to let them send you an invitation.
 ** Invitation links can be open with any Olvid application or open in a web browser to show a QR code to scan.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: identity not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message IdentityGetInvitationLinkRequest {}
message IdentityGetInvitationLinkResponse {
  string invitation_link = 1;
}

/*
 ** IdentityUpdateDetails
 ** Update your Olvid identity details (first name, last name, company and position).
 ** At least on field in first and last name must be non empty.
 ** Your details will be visible by your contacts, and you display name is computed from this details.
 ** Details for a keycloak managed identity cannot be updated.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: identity not found.
 ** `INVALID_ARGUMENT`: at least one of first name and last name must be non empty / cannot update a keycloak managed identity.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentityUpdateDetailsRequest {
  // your new identity details
  datatypes.v1.IdentityDetails new_details = 2;
}
message IdentityUpdateDetailsResponse {}

/*
 ** IdentitySetPhoto
 ** Set a profile picture for your identity.
 ** This picture will be visible by your contacts.
 ** The photo can be jpeg or png but will be converted to jpeg and resolution will be limited to 1080x1080.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: identity not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message IdentitySetPhotoRequestMetadata {
  string filename = 1;
  uint64 file_size = 2;
}
message IdentitySetPhotoRequest {
  oneof request {
    IdentitySetPhotoRequestMetadata metadata = 1;
    bytes payload = 2;
  }
}
message IdentitySetPhotoResponse {}

/*
 ** IdentityDownloadPhoto
 ** Download your current identity picture.
 ** Pictures are always jpeg files with a maximum of 1080x1080 resolution.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: identity not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message IdentityDownloadPhotoRequest {}
message IdentityDownloadPhotoResponse {
  bytes photo = 1;
}

/*
 ** IdentityRemovePhoto
 ** Remove your current identity picture.
 ** The automatically generate identity image will be used instead.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: identity not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message IdentityRemovePhotoRequest {}
message IdentityRemovePhotoResponse {}

/*
 ** IdentityGetApiKeyStatus
 ** Check you current Olvid api key status.
 ** Api Keys allows an identity to initiate calls or to use multi device.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentityGetApiKeyStatusRequest {}
message IdentityGetApiKeyStatusResponse {
  datatypes.v1.Identity.ApiKey api_key = 1;
}

/*
 ** IdentitySetApiKey
 ** Manually set an Olvid api key.
 ** Olvid api keys are standard uuids.
 **
 ** **Error codes**:
 ** `INVALID_ARGUMENT`: api key format is not valid.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentitySetApiKeyRequest {
  string api_key = 1;
}
message IdentitySetApiKeyResponse {
  datatypes.v1.Identity.ApiKey api_key = 1;
}

/*
 ** IdentitySetConfigurationLink
 ** Set an Olvid configuration link with an api key.
 **
 ** **Error codes**:
 ** `INVALID_ARGUMENT`: configuration link is invalid / configuration link is for another server.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message IdentitySetConfigurationLinkRequest {
  string configuration_link = 1;
}
message IdentitySetConfigurationLinkResponse {
  datatypes.v1.Identity.ApiKey api_key = 1;
}
