syntax = "proto3";

package olvid.daemon.command.v1;

import "olvid/daemon/datatypes/v1/invitation.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** InvitationList
 ** List invitations for current identity.
 ** Pass a filter to select only invitations that match specific criteria.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INVALID_ARGUMENT`: invalid filter.
 ** `INTERNAL`
 */
message InvitationListRequest {
  optional datatypes.v1.InvitationFilter filter = 1;
}
message InvitationListResponse {
  repeated datatypes.v1.Invitation invitations = 1;
}

/*
 ** InvitationGet
 ** Get invitation by id.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: invitation not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message InvitationGetRequest {
  uint64 invitation_id = 1;
}
message InvitationGetResponse {
  datatypes.v1.Invitation invitation = 1;
}

/*
 ** InvitationNew
 ** Send an invitation to another Olvid user using its invitation link.
 ** Invitation links starts with https://invitation.olvid.io#.
 ** Sending an invitation will initiate an invitation protocol and create a new Invitation.
 **
 ** **Error codes**:
 ** `INVALID_ARGUMENT`: you cannot invite yourself / invitation link is invalid.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message InvitationNewRequest {
  string invitation_url = 1;
}

message InvitationNewResponse {
  datatypes.v1.Invitation invitation = 1;
}

/*
 ** InvitationAccept
 ** Accept a pending invitation. This will allow protocol to continue.
 ** This command is only possible if `invitation.status` is one of the following:
 **  - STATUS_INVITATION_WAIT_YOU_TO_ACCEPT
 **  - STATUS_INTRODUCTION_WAIT_YOU_TO_ACCEPT
 **  - STATUS_ONE_TO_ONE_INVITATION_WAIT_YOU_TO_ACCEPT
 **  - STATUS_GROUP_INVITATION_WAIT_YOU_TO_ACCEPT
 **
 ** **Error codes**:
 ** `NOT_FOUND`: invitation not found.
 ** `INVALID_ARGUMENT`: cannot accept an invitation with this status.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message InvitationAcceptRequest {
  uint64 invitation_id = 1;
}
message InvitationAcceptResponse {}

/*
 ** InvitationDecline
 ** Decline a pending invitation. This will abort protocol.
 ** For invitation, introduction and one to one invitation the other user is not notified you declined the invitation.
 ** This command is only possible if `invitation.status` is one of the following:
 **  - STATUS_INVITATION_WAIT_YOU_TO_ACCEPT
 **  - STATUS_INTRODUCTION_WAIT_YOU_TO_ACCEPT
 **  - STATUS_ONE_TO_ONE_INVITATION_WAIT_YOU_TO_ACCEPT
 **  - STATUS_GROUP_INVITATION_WAIT_YOU_TO_ACCEPT
 **
 ** **Error codes**:
 ** `NOT_FOUND`: invitation not found.
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INTERNAL`
 */
message InvitationDeclineRequest {
  uint64 invitation_id = 1;
}
message InvitationDeclineResponse {}

/*
 ** InvitationSas
 ** Only possible if `invitation.status` is equal to STATUS_INVITATION_WAIT_YOU_FOR_SAS_EXCHANGE.
 ** Set the 4 digit code shown on your partner device.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: invitation not found.
 ** `INVALID_ARGUMENT`: unexpected invitation status.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message InvitationSasRequest {
  uint64 invitation_id = 1;
  // 4 digit pin code shown on your partner device
  string sas = 2;
}
message InvitationSasResponse {}

/*
 ** InvitationDelete
 ** Abort the protocol associated to any invitation and delete this invitation.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message InvitationDeleteRequest {
  uint64 invitation_id = 1;
}
message InvitationDeleteResponse {}
