syntax = "proto3";

package olvid.daemon.command.v1;

import "olvid/daemon/datatypes/v1/settings.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** SettingsIdentityGet
 ** Get current settings for your identity.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SettingsIdentityGetRequest {}
message SettingsIdentityGetResponse {
  datatypes.v1.IdentitySettings identity_settings = 1;
}

/*
 ** SettingsIdentitySet
 ** Update your identity settings.
 ** ⚠️ Update erase the WHOLE settings.
 ** To update current settings use SettingsIdentityGet to get current config, and only edit fields you want to update.
 **
 ** **Error codes**:
 ** `INVALID_ARGUMENT`: cannot set keycloak settings if your identity is not keycloak managed.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SettingsIdentitySetRequest {
  datatypes.v1.IdentitySettings identity_settings = 1;
}
message SettingsIdentitySetResponse {
  datatypes.v1.IdentitySettings identity_settings = 1;
}

/*
 ** SettingsDiscussionGet
 ** Get a discussion settings.
 ** Those settings are shared with other members of this discussion.
 ** For example, a parameter for ephemeral message parameters concerning a discussion would affect all future messages posted in this discussion, from any member.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: discussion not found
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SettingsDiscussionGetRequest {
  uint64 discussion_id = 1;
}
message SettingsDiscussionGetResponse {
  datatypes.v1.DiscussionSettings discussion_settings = 1;
}

/*
 ** SettingsDiscussionSet
 ** Update a discussion settings.
 ** ⚠️ Update erase the WHOLE settings.
 ** To update current settings use SettingsDiscussionGet to get current config, and only edit fields you want to update.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: discussion not found
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SettingsDiscussionSetRequest {
  datatypes.v1.DiscussionSettings discussion_settings = 1;
}
message SettingsDiscussionSetResponse {
  datatypes.v1.DiscussionSettings discussion_settings = 1;
}
