syntax = "proto3";

package olvid.daemon.command.v1;

import "olvid/daemon/datatypes/v1/storage.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** StorageList
 ** List stored elements in global storage scope, for current client key.
 ** Pass a filter to select only elements that match specific criteria.
 **
 ** Mind that temporary client keys (specified in daemon environment or as command line arguments) does not have an allocated storage space.
 ** You must create a client in database to use storage commands.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid or a temporary client key.
 ** `INVALID_ARGUMENT`: invalid filter
 ** `INTERNAL`
 */
message StorageListRequest {
  optional datatypes.v1.StorageElementFilter filter = 1;
}
message StorageListResponse {
  repeated datatypes.v1.StorageElement elements = 1;
}

/*
 ** StorageGet
 ** Request the value associated to a key in your global storage.
 ** If the key does not already exists return an empty string.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid or a temporary client key.
 */
message StorageGetRequest {
  string key = 1;
}
message StorageGetResponse {
  string value = 1;
}

/*
 ** StorageSet
 ** Set the value for a key in your global storage.
 ** If the key was already set the value is updated and it returns the *previous_value* in response.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid or a temporary client key.
 ** `INTERNAL`
 */
message StorageSetRequest {
  string key = 1;
  string value = 2;
}
message StorageSetResponse {
  string previous_value = 1; // if the key already exists, this contains the erased value.
}

/*
 ** StorageUnset
 ** Unset a key in your global storage.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid or a temporary client key.
 */
message StorageUnsetRequest {
  string key = 1;
}
message StorageUnsetResponse {
  string previous_value = 1; // the value previously associated to this key
}

/*
 ** DiscussionStorageList
 ** List stored elements in a specific discussion storage scope, for current client key.
 ** Pass a filter to select only elements that match specific criteria.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid or a temporary client key.
 ** `INVALID_ARGUMENT`: discussion storage is not available with an admin client key / invalid filter.
 ** `NOT_FOUND`: discussion not found.
 ** `INTERNAL`
 */
message DiscussionStorageListRequest {
  uint64 discussion_id = 1;
  optional datatypes.v1.StorageElementFilter filter = 2;
}

message DiscussionStorageListResponse {
  repeated datatypes.v1.StorageElement elements = 1;
}

/*
 ** DiscussionStorageGet
 ** Request the value associated to a key in the specified discussion storage.
 ** If the key does not already exists return an empty string.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid or a temporary client key.
 ** `INVALID_ARGUMENT`: discussion storage is not available with an admin client key.
 ** `NOT_FOUND`: discussion not found.
 */
message DiscussionStorageGetRequest {
  uint64 discussion_id = 1;
  string key = 2;
}
message DiscussionStorageGetResponse {
  string value = 1;
}

/*
 ** DiscussionStorageSet
 ** Set the value for a key in the specified discussion storage.
 ** If the key was already set the value is updated and it returns the *previous_value* in response.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid or a temporary client key.
 ** `INVALID_ARGUMENT`: discussion storage is not available with an admin client key.
 ** `NOT_FOUND`: discussion not found.
 ** `INTERNAL`
 */
message DiscussionStorageSetRequest {
  uint64 discussion_id = 1;
  string key = 2;
  string value = 3;
}
message DiscussionStorageSetResponse {
  string previous_value = 1;
}

/*
 ** DiscussionStorageUnset
 ** Unset a key in the specified discussion storage.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid or a temporary client key.
 ** `INVALID_ARGUMENT`: discussion storage is not available with an admin client key.
 ** `NOT_FOUND`: discussion not found.
 */
message DiscussionStorageUnsetRequest {
  uint64 discussion_id = 1;
  string key = 2;
}
message DiscussionStorageUnsetResponse {
  string previous_value = 1;
}
