syntax = "proto3";

package olvid.daemon.command.v1;

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** Ping
 ** Unauthenticated method.
 ** Just check if daemon is reachable.
 */
message PingRequest {}
message PingResponse {}

/*
 ** DaemonVersion
 ** Authenticated method.
 ** Ask daemon its version.
 */
message DaemonVersionRequest {}
message DaemonVersionResponse {
  string version = 1;
}

/*
 ** AuthenticationTest
 ** Authenticated rpc.
 ** Check that sent credentials are valid user credentials, else it returns an error.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: invalid client key.
 */
message AuthenticationTestRequest {}
message AuthenticationTestResponse {}

/*
 ** AuthenticationAdminTest
 ** Authenticated rpc (admin key only).
 ** Check that sent credentials are valid admin credentials, else it returns an error.
 **
 ** **Error codes**:
 ** `PERMISSION_DENIED`: client key is not an admin client key.
 */
message AuthenticationAdminTestRequest {}
message AuthenticationAdminTestResponse {}
