syntax = "proto3";

package olvid.daemon.notification.v1;

import "olvid/daemon/datatypes/v1/attachment.proto";
import "olvid/daemon/datatypes/v1/message.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** AttachmentReceived
 ** Receive a notification every time you receive an attachment in a discussion (one-to-one or group discussion).
 ** When you receive a message with multiple attachments, you will receive one notification for each attachment.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToAttachmentReceivedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about attachments that match all the filter params.
  optional datatypes.v1.AttachmentFilter filter = 2;
}
message AttachmentReceivedNotification {
  datatypes.v1.Attachment attachment = 1;
}

/*
 ** AttachmentUploaded
 ** Receive a notification every time an attachment you sent has been marked as uploaded.
 ** A message with attachments is delivered to recipients only when all attachments have been uploaded.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 ** `INVALID_ARGUMENT`: cannot subscribe for non-outbound messages.
 ** `NOT_FOUND`: at least one of the _message_ids_ is incorrect.
 */
message SubscribeToAttachmentUploadedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about attachments that match all the filter params.
  optional datatypes.v1.AttachmentFilter filter = 2;
  // you will only receive notifications about attachments related to messages specified in this list.
  repeated datatypes.v1.MessageId message_ids = 3;
  // you will only receive notifications about attachments specified in this list.
  repeated datatypes.v1.AttachmentId attachment_ids = 4;
}
message AttachmentUploadedNotification {
  datatypes.v1.Attachment attachment = 1;
}
