syntax = "proto3";

package olvid.daemon.notification.v1;

import "olvid/daemon/datatypes/v1/call.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** CallIncomingCall
 ** Receive a notification when someone tries to call you. (InboundCal)
 ** Daemon will automatically answer with a busy message to notify you won't be able to answer.
 ** Call details are available in notification content.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToCallIncomingCallNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
}
message CallIncomingCallNotification {
  string call_identifier = 1;
  // set to group discussion if calling a group, else to contact's discussion, even if there are multiple participants
  uint64 discussion_id = 2;
  datatypes.v1.CallParticipantId participant_id = 3; // obviously contains a contact id
  string caller_display_name = 4;
  uint32 participant_count = 5;
}

/*
 ** CallRinging
 ** When you initiated a call, receive a notification when a participant phone starts to ring.
 ** Under some network circumstances a participant phone might never start ringing.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToCallRingingNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
}
message CallRingingNotification {
  string call_identifier = 1;
  datatypes.v1.CallParticipantId participant_id = 2;
}

/*
 ** CallAccepted
 ** When you initiated a call, receive a notification if a participant accepted the call.
 ** Daemon will automatically hang up when a participant accept the call because we currently cannot manage the call.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToCallAcceptedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
}
message CallAcceptedNotification {
  string call_identifier = 1;
  datatypes.v1.CallParticipantId participant_id = 2;
}

/*
 ** CallDeclined
 ** When you initiated a call, receive a notification if a participant declined the call.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToCallDeclinedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
}
message CallDeclinedNotification {
  string call_identifier = 1;
  datatypes.v1.CallParticipantId participant_id = 2;
}

/*
 ** CallBusy (Outbound call)
 ** When you initiated a call, receive a notification if a participant accepted the call.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToCallBusyNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
}
message CallBusyNotification {
  string call_identifier = 1;
  datatypes.v1.CallParticipantId participant_id = 2;
}

/*
 ** CallEnded:
 ** For inbound or outbound call, receive a notification when every call participant left a call or declined it.
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToCallEndedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
}
message CallEndedNotification {
  string call_identifier = 1;
}
