syntax = "proto3";

package olvid.daemon.notification.v1;

import "olvid/daemon/datatypes/v1/group.proto";

option go_package = "olvid.io/daemon";
option java_multiple_files = true;
option java_package = "io.olvid.desktop.daemon.protobuf";

/*
 ** GroupNew
 ** Receive a notification each time you join a new group.
 ** This can happen under different circumstances:
 ** - you created a group
 ** - you accepted a group invitation
 ** - for keycloak managed group: the directory created a group or added you to an existing group
 **
 ** **Error codes**:
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupNewNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 2;
}
message GroupNewNotification {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupDeleted
 ** Receive a notification each time you leave a group.
 ** This can happen under different circumstances:
 ** - you chose to leave a group
 ** - you disbanded a group (you must be admin of this group)
 ** - a group admin disbanded the group
 ** - a group admin removed you from the group
 ** - for keycloak managed group: the keycloak directory removed you from the group or disbanded the group
 **
 ** **Error codes**:
 ** `NOT_FOUND`: at least one of the _group_ids_ does not exist.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupDeletedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups specified in this list.
  repeated uint64 group_ids = 2;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 3;
}
message GroupDeletedNotification {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupNameUpdated
 ** Receive a notification each time a group name have been updated.
 ** This can happen under different circumstances:
 ** - you updated the group name (you must be admin of this group)
 ** - an admin updated the group name
 ** - for keycloak managed groups: the group name were changed by the keycloak directory
 **
 ** **Error codes**:
 ** `NOT_FOUND`: at least one of the _group_ids_ does not exists.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupNameUpdatedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups specified in this list.
  repeated uint64 group_ids = 2;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 3;
  // regexp filter on *group.name* field, before update
  optional string previous_name_search = 4;
}
message GroupNameUpdatedNotification {
  datatypes.v1.Group group = 1;
  // the group name before update
  string previous_name = 2;
}

/*
 ** GroupPhotoUpdated
 ** Receive a notification when a group picture have been updated.
 ** This can happen under different circumstances:
 ** - you updated the group picture (you must be admin of this group)
 ** - an admin updated the group picture
 ** - for keycloak managed groups: the group picture were changed by the keycloak directory
 **
 ** **Error codes**:
 ** `NOT_FOUND`: at least one of the _group_ids_ does not exists.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupPhotoUpdatedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups specified in this list.
  repeated uint64 group_ids = 2;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 3;
}
message GroupPhotoUpdatedNotification {
  datatypes.v1.Group group = 1;
}

/*
 ** GroupDescriptionUpdated
 ** Receive a notification when a group description have been updated.
 ** This can happen under different circumstances:
 ** - you updated the group description (you must be admin of this group)
 ** - an admin updated the group description
 ** - for keycloak managed groups: the group description were changed by the keycloak directory
 **
 ** **Error codes**:
 ** `NOT_FOUND`: at least one of the _group_ids_ does not exists.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupDescriptionUpdatedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups specified in this list.
  repeated uint64 group_ids = 2;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 3;
  // regexp filter on previous *group.description* field, before update
  optional string previous_description_search = 4;
}
message GroupDescriptionUpdatedNotification {
  datatypes.v1.Group group = 1;
  string previous_description = 2;
}

/*
 ** GroupPendingMemberAdded
 ** Receive a notification when a pending member was added from a group.
 ** This can happen under different circumstances:
 ** - an admin added a new member to the group
 ** - you joined a group and all group members are all considered as pending until each one acknowledge you joined this group
 **
 ** **Error codes**:
 ** `NOT_FOUND`: at least one of the _group_ids_ does not exists.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupPendingMemberAddedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups specified in this list.
  repeated uint64 group_ids = 2;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 3;
  // you will only receive notifications about groups with a pending member that match this filter.
  optional datatypes.v1.PendingGroupMemberFilter pending_member_filter = 4;
}
message GroupPendingMemberAddedNotification {
  datatypes.v1.Group group = 1;
  datatypes.v1.PendingGroupMember pending_member = 2;
}

/*
 ** GroupPendingMemberRemoved
 ** Receive a notification when a pending member was removed from a group.
 ** This can happen under different circumstances:
 ** - a pending group member accepted or declined the group invitation
 ** - you joined a group and a member acknowledged you joined this group
 **
 ** **Error codes**:
 ** `NOT_FOUND`: at least one of the _group_ids_ does not exists.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupPendingMemberRemovedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups specified in this list.
  repeated uint64 group_ids = 2;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 3;
  // you will only receive notifications about groups with a pending member that match this filter.
  optional datatypes.v1.PendingGroupMemberFilter pending_member_filter = 4;
}
message GroupPendingMemberRemovedNotification {
  datatypes.v1.Group group = 1;
  datatypes.v1.PendingGroupMember pending_member = 2;
}

/*
 ** GroupMemberJoined
 ** Receive a notification when a new member joined a group.
 ** This can happen under different circumstances:
 ** - a pending group member accepted the group invitation
 ** - for keycloak managed groups: directory added a new group member / a user registered on directory and was automatically added to existing groups
 **
 ** **Error codes**:
 ** `NOT_FOUND`: at least one of the _group_ids_ does not exists.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupMemberJoinedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups specified in this list.
  repeated uint64 group_ids = 2;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 3;
  // you will only receive notifications about groups with a member that match this filter.
  optional datatypes.v1.GroupMemberFilter member_filter = 4;
}
message GroupMemberJoinedNotification {
  datatypes.v1.Group group = 1;
  datatypes.v1.GroupMember member = 2;
}

/*
 ** GroupMemberLeft
 ** Receive a notification when a group member was removed from a group.
 ** This can happen under different circumstances:
 ** - you removed a group member (you must be a group admin)
 ** - a group member was removed by an admin
 ** - for keycloak managed groups: directory removed a group member / a user unregistered from directory and was automatically removed from groups
 **
 ** **Error codes**:
 ** `NOT_FOUND`: at least one of the _group_ids_ does not exists.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupMemberLeftNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups specified in this list.
  repeated uint64 group_ids = 2;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 3;
  // you will only receive notifications about groups with a member that match this filter.
  optional datatypes.v1.GroupMemberFilter member_filter = 4;
}
message GroupMemberLeftNotification {
  datatypes.v1.Group group = 1;
  datatypes.v1.GroupMember member = 2;
}

/*
 ** GroupOwnPermissionsUpdated
 ** Receive a notification when your permissions have been updated in a group.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: at least one of the _group_ids_ does not exists.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupOwnPermissionsUpdatedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups specified in this list.
  repeated uint64 group_ids = 2;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 3;
  // you will only receive notifications about groups where your permissions match this filter.
  optional datatypes.v1.GroupPermissionFilter permissions_filter = 4;
  // you will only receive notifications when your previous permissions match this filter.
  optional datatypes.v1.GroupPermissionFilter previous_permissions_filter = 5;
}
message GroupOwnPermissionsUpdatedNotification {
  datatypes.v1.Group group = 1;
  // your new permissions
  datatypes.v1.GroupMemberPermissions permissions = 2;
  // your permissions before update
  datatypes.v1.GroupMemberPermissions previous_permissions = 3;
}

/*
 ** GroupMemberPermissionsUpdated
 ** Receive a notification when a group member permissions have been updated.
 **
 ** **Error codes**:
 ** `NOT_FOUND`: at least one of the _group_ids_ does not exists.
 ** `UNAUTHENTICATED`: client key is invalid.
 */
message SubscribeToGroupMemberPermissionsUpdatedNotification {
  // limit the number of notifications you will receive , set to 0 to disable
  optional uint64 count = 1;
  // you will only receive notifications about groups specified in this list.
  repeated uint64 group_ids = 2;
  // you will only receive notifications about groups that match all the filter params.
  optional datatypes.v1.GroupFilter group_filter = 3;
  // you will only receive notifications about group members that match this filter.
  optional datatypes.v1.GroupMemberFilter member_filter = 4;
  // you will only receive notifications when previous permissions match this filter.
  optional datatypes.v1.GroupPermissionFilter previous_permission_filter = 5;
}
message GroupMemberPermissionsUpdatedNotification {
  datatypes.v1.Group group = 1;
  // the group member permissions have been updated for
  datatypes.v1.GroupMember member = 2;
  // the member permissions before update
  datatypes.v1.GroupMemberPermissions previous_permissions = 3;
}
